In [7]:
import pandas as pd

<h1>1. Student dateframe</h1>

In [44]:
df_student = pd.DataFrame({
    'id': [1, 2, 3, 4, 5, 6],
    'science_score': [None, 0, 0, 0, 0, 0],
    'english_score': [None, 0, 0, 0, 0, 0]
}).convert_dtypes(dtype_backend='pyarrow')

df_student

   id  science_score  english_score
0   1           <NA>           <NA>
1   2              0              0
2   3              0              0
3   4              0              0
4   5              0              0
5   6              0              0

<h1>2. Score dataframe</h1>

In [45]:
df_score = pd.DataFrame({
    'id': [4, 5, 6],
    'science_score': [40, 50, 60],
    'english_score': [44, 55, 66]
}).convert_dtypes(dtype_backend='pyarrow')

df_score

   id  science_score  english_score
0   4             40             44
1   5             50             55
2   6             60             66

<h1>3. merge two dataframes with indicator=True</h1>

In [46]:
df_merged = df_student.merge(df_score, left_on=['id'], right_on=['id'], how='left', suffixes=('', '_r'), indicator=True)
df_merged = df_merged.convert_dtypes(dtype_backend='pyarrow')
df_merged

,id,science_score,english_score,science_score_r,english_score_r,_merge
0,1,<NA>,<NA>,<NA>,<NA>,left_only
1,2,0,0,<NA>,<NA>,left_only
2,3,0,0,<NA>,<NA>,left_only
3,4,0,0,40,44,both
4,5,0,0,50,55,both
5,6,0,0,60,66,both

<h1>4. Update the merged rows if df_merged['_merge'] == 'both'</h1>
<h4>Multiple columns</h4>

In [47]:
# df_merged['science_score'] = df_merged['science_score'].astype('int64[pyarrow]')
# df_merged['english_score'] = df_merged['english_score'].astype('int64[pyarrow]')

condition = df_merged['_merge'] == 'both'
update_columns = ['science_score', 'english_score']
source_columns = [f'{i}_r' for i in update_columns]

df_merged.loc[condition, update_columns] = df_merged.loc[condition, source_columns].to_numpy()
df_merged

,id,science_score,english_score,science_score_r,english_score_r,_merge
0,1,<NA>,<NA>,<NA>,<NA>,left_only
1,2,0,0,<NA>,<NA>,left_only
2,3,0,0,<NA>,<NA>,left_only
3,4,40,44,40,44,both
4,5,50,55,50,55,both
5,6,60,66,60,66,both

In [42]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               6 non-null      int64[pyarrow]
 1   science_score    6 non-null      int64[pyarrow]
 2   english_score    6 non-null      int64[pyarrow]
 3   science_score_r  3 non-null      int64[pyarrow]
 4   english_score_r  3 non-null      int64[pyarrow]
 5   _merge           6 non-null      category
dtypes: category(1), int64[pyarrow](5)
memory usage: 514.0 bytes

<h1>5. Select only the column in the df_student dataframe</h1>

In [49]:
df_merged.loc[:, list(df_student.columns)]

   id  science_score  english_score
0   1           <NA>           <NA>
1   2              0              0
2   3              0              0
3   4             40             44
4   5             50             55
5   6             60             66