In [2]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'id': [1, 2, 3, None, None, None],
    'score': [20, 20, 100, 10, 10, 10]
}).convert_dtypes(dtype_backend='pyarrow')

df

     id  score
0     1     20
1     2     20
2     3    100
3  <NA>     10
4  <NA>     10
5  <NA>     10

In [5]:
condition = df['id'].isnull()
condition

0    False
1    False
2    False
3     True
4     True
5     True
Name: id, dtype: bool

In [6]:
df.loc[condition, :]

     id  score
3  <NA>     10
4  <NA>     10
5  <NA>     10

<h1>~ is the negate operator</h1>

In [7]:
df.loc[(~condition), :]

   id  score
0   1     20
1   2     20
2   3    100