<h1>1. By default, pandas create an index based range index</h1>

In [45]:
import pandas as pd

data = {
    'name': ['Student 1', 'Student 2', 'Student 3'],
    'score': [71, 72, 73],
}

df = pd.DataFrame(data).convert_dtypes(dtype_backend='pyarrow')

df

        name  score
0  Student 1     71
1  Student 2     72
2  Student 3     73

<h1>2. set_index()</h1>
<h4>set_index() is not repeatable, need to make sure the dataframe has a range index (default index) before calling it</h4>

In [62]:
df = pd.DataFrame(data).convert_dtypes(dtype_backend='pyarrow')
df = df.set_index('name')
df

           score
name
Student 1     71
Student 2     72
Student 3     73

<h1>3. reset_index()</h1>
<h4>reset_index() is not repeatable, need to make sure the dataframe has a non-default index before calling it</h4>

In [48]:
df = pd.DataFrame(data).convert_dtypes(dtype_backend='pyarrow').set_index('name')
df = df.reset_index()
df

        name  score
0  Student 1     71
1  Student 2     72
2  Student 3     73

<h1>4. Once become the index, the column is no longer accessible by name</h1>
<h4>Need to access it by df.index</h4>

In [74]:
df = pd.DataFrame(data).convert_dtypes(dtype_backend='pyarrow')
df = df.set_index('name')

df.loc[df.index == 'Student 1', :]

# The following (access by name) is a run-time error
# df.loc[~df['name'].isnull, :]

           score
name
Student 1     71

<h1>5. Duplicate index values are possible</h1>

In [81]:
df_1 = pd.DataFrame({
    'name': ['Student 1', 'Student 2', 'Student 3'],
    'score': [71, 72, 73],
}).convert_dtypes(dtype_backend='pyarrow')

df_2 = pd.DataFrame({
    'name': ['Student 4', 'Student 5', 'Student 6'],
    'score': [74, 75, 76],
}).convert_dtypes(dtype_backend='pyarrow')

df = pd.concat([df_1, df_2])
df

        name  score
0  Student 1     71
1  Student 2     72
2  Student 3     73
0  Student 4     74
1  Student 5     75
2  Student 6     76

<h1>6. Duplicate indices do not affect .loc[] result</h1>

In [97]:
df_1 = pd.DataFrame({
    'name': ['Student 1', 'Student 2', 'Student 3'],
    'score': [71, 72, 73],
}).convert_dtypes(dtype_backend='pyarrow')

df_2 = pd.DataFrame({
    'name': ['Student 4', 'Student 5', 'Student 6'],
    'score': [74, 75, 76],
}).convert_dtypes(dtype_backend='pyarrow')

df = pd.concat([df_1, df_2])
df.loc[df['name'].str.lower() == 'student 3', :]

        name  score
2  Student 3     73