In [2]:
import pandas as pd
from datetime import date, datetime

In [49]:
df = pd.DataFrame({
    'id': [1, 2, 3, 4],
    'date': [date(2025, 1, 1), date(2025, 1, 2), date(2025, 1, 3), None]
}).convert_dtypes(dtype_backend='pyarrow')

# For some reason convert_dtypes keeps the date column as object
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      4 non-null      int64[pyarrow]
 1   date    3 non-null      object
dtypes: int64[pyarrow](1), object(1)
memory usage: 196.0+ bytes

   id        date
0   1  2025-01-01
1   2  2025-01-02
2   3  2025-01-03
3   4        None

<h1>The date comparison works fine with object type</h1>

In [47]:
df.loc[(df['date'] <= date(2025, 1, 2)) | df['date'].isnull(), :]

   id        date
0   1  2025-01-01
1   2  2025-01-02
3   4        <NA>

In [43]:
# For some reason convert_dtypes keeps the date column as object
df['date'] = df['date'].astype('date32[pyarrow]')
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      4 non-null      int64[pyarrow]
 1   date    3 non-null      date32[day][pyarrow]
dtypes: date32[day][pyarrow](1), int64[pyarrow](1)
memory usage: 181.0 bytes

   id        date
0   1  2025-01-01
1   2  2025-01-02
2   3  2025-01-03
3   4        <NA>

<h1>The date comparison works fine with date32[pyarrow] type as well</h1>

In [48]:
df.loc[(df['date'] <= date(2025, 1, 2)) | df['date'].isnull(), :]

   id        date
0   1  2025-01-01
1   2  2025-01-02
3   4        <NA>

<h1>In python</h1>
<h1>It is a run-time error to compare datetime.datetime to datetime.date</h1>

In [12]:
now = datetime.now()
d = date.fromisoformat(now.strftime('%Y-%m-%d'))

if now > d:
    print('fine')

TypeError: can't compare datetime.datetime to datetime.date